#!/usr/bin/env ruby

# frozen_string_literal: true

require "thor"
require "xvert"

class CLI < Thor
  class << self
    def exit_on_failure?
      true
    end
  end

  desc "jy", "Convert JSON to YAML"
  def jy
    puts Xvert.json_to_yaml($stdin.readlines.join)
  end
end

CLI.start(ARGV)
