#!/usr/bin/env ruby

# frozen_string_literal: true

require "thor"
require "xvert"

class CLI < Thor
  desc "jy", "Convert JSON to YAML"
  def jy
    puts Xvert.json_to_yaml(STDIN.readlines.join)
  end
end

CLI.start(ARGV)
